# Generated by Django 3.1.1 on 2020-09-20 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviereview_app', '0002_auto_20200920_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_reactions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
