# Generated by Django 3.1.1 on 2020-09-20 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview_app', '0003_article_users_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_embed',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
