# Generated by Django 3.1.1 on 2020-09-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview_app', '0005_auto_20200920_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='users_reactions',
            new_name='users_ratings',
        ),
    ]
