# Generated by Django 3.1.1 on 2020-09-21 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moviereview_app', '0006_auto_20200921_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='users_ratings',
            new_name='users_reactions',
        ),
    ]
