# Generated by Django 3.1.1 on 2020-09-22 18:18

from django.db import migrations, models
import moviereview_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview_app', '0007_auto_20200921_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=moviereview_app.models.generate_filename),
        ),
    ]
