# Generated by Django 3.1.1 on 2020-09-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview_app', '0008_auto_20200922_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='votes',
            field=models.FloatField(default=0),
        ),
    ]
