# Generated by Django 3.1.1 on 2020-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview_app', '0009_auto_20200923_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ranking',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
