# Generated by Django 3.1.1 on 2020-09-23 15:39

from django.db import migrations, models
import moviereview_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview_app', '0010_auto_20200923_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='Other/your-image-here.jpg', upload_to=moviereview_app.models.generate_filename),
        ),
    ]
